<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="4" ignored="2" total="11" passed="4">
  <reporter-output>
    <line>
      <![CDATA[<a href="E:\screenshot\error.jpg" target="_blank">Screenshot link</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a href="E:\screenshot\error.jpg" target="_blank"><img height=200 width=200 src="E:\screenshot\error.jpg"></a>]]>
    </line>
    <line>
      <![CDATA[<a href="E:\screenshot\error.jpg" target="_blank">Screenshot link</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a href="E:\screenshot\error.jpg" target="_blank"><img height=200 width=200 src="E:\screenshot\error.jpg"></a>]]>
    </line>
    <line>
      <![CDATA[<a href="E:\screenshot\error.jpg" target="_blank">Screenshot link</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a href="E:\screenshot\error.jpg" target="_blank"><img height=200 width=200 src="E:\screenshot\error.jpg"></a>]]>
    </line>
    <line>
      <![CDATA[<a href="E:\screenshot\error.jpg" target="_blank">Screenshot link</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a href="E:\screenshot\error.jpg" target="_blank"><img height=200 width=200 src="E:\screenshot\error.jpg"></a>]]>
    </line>
  </reporter-output>
  <suite name="Master Suite" duration-ms="0" started-at="2021-04-07T13:02:44 IST" finished-at="2021-04-07T13:02:44 IST">
    <groups>
    </groups>
  </suite> <!-- Master Suite -->
  <suite name="Regression Suite" duration-ms="232" started-at="2021-04-07T13:02:43 IST" finished-at="2021-04-07T13:02:44 IST">
    <groups>
    </groups>
    <test name="Regression LoginTest" duration-ms="26" started-at="2021-04-07T13:02:43 IST" finished-at="2021-04-07T13:02:43 IST">
      <class name="regression.TestCase1">
        <test-method status="PASS" signature="creatingDBConn()[pri:0, instance:regression.TestCase1@22635ba0]" name="creatingDBConn" is-config="true" duration-ms="0" started-at="2021-04-07T13:02:43 IST" finished-at="2021-04-07T13:02:43 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- creatingDBConn -->
        <test-method status="PASS" signature="doUserReg()[pri:1, instance:regression.TestCase1@22635ba0]" name="doUserReg" duration-ms="2" started-at="2021-04-07T13:02:43 IST" finished-at="2021-04-07T13:02:43 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doUserReg -->
        <test-method status="PASS" signature="launchBrowser()[pri:0, instance:regression.TestCase1@22635ba0]" name="launchBrowser" is-config="true" duration-ms="0" started-at="2021-04-07T13:02:43 IST" finished-at="2021-04-07T13:02:43 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:regression.TestCase1@22635ba0]" name="closeBrowser" is-config="true" duration-ms="0" started-at="2021-04-07T13:02:43 IST" finished-at="2021-04-07T13:02:43 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method status="PASS" signature="launchBrowser()[pri:0, instance:regression.TestCase1@22635ba0]" name="launchBrowser" is-config="true" duration-ms="2" started-at="2021-04-07T13:02:43 IST" finished-at="2021-04-07T13:02:43 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method status="PASS" signature="doLogin()[pri:2, instance:regression.TestCase1@22635ba0]" name="doLogin" duration-ms="3" started-at="2021-04-07T13:02:43 IST" finished-at="2021-04-07T13:02:43 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogin -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:regression.TestCase1@22635ba0]" name="closeBrowser" is-config="true" duration-ms="5" started-at="2021-04-07T13:02:43 IST" finished-at="2021-04-07T13:02:43 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method status="PASS" signature="closeDBConn()[pri:0, instance:regression.TestCase1@22635ba0]" name="closeDBConn" is-config="true" duration-ms="1" started-at="2021-04-07T13:02:43 IST" finished-at="2021-04-07T13:02:43 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDBConn -->
      </class> <!-- regression.TestCase1 -->
    </test> <!-- Regression LoginTest -->
    <test name="Regression Validate Title Test" duration-ms="30" started-at="2021-04-07T13:02:44 IST" finished-at="2021-04-07T13:02:44 IST">
      <class name="regression.TestCase2">
        <test-method status="FAIL" signature="validateTitle()[pri:0, instance:regression.TestCase2@2133814f]" name="validateTitle" duration-ms="3" started-at="2021-04-07T13:02:44 IST" finished-at="2021-04-07T13:02:44 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [Yahoo.com] but found [Google.com],
Title Didnt Match expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Yahoo.com] but found [Google.com],
Title Didnt Match expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at regression.TestCase2.validateTitle(TestCase2.java:22)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1213)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<a href="E:\screenshot\error.jpg" target="_blank">Screenshot link</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a href="E:\screenshot\error.jpg" target="_blank"><img height=200 width=200 src="E:\screenshot\error.jpg"></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- validateTitle -->
      </class> <!-- regression.TestCase2 -->
    </test> <!-- Regression Validate Title Test -->
  </suite> <!-- Regression Suite -->
  <suite name="Functional Suite" duration-ms="1167" started-at="2021-04-07T13:02:42 IST" finished-at="2021-04-07T13:02:43 IST">
    <groups>
      <group name="functional">
        <method signature="TestCase1.doLogin()[pri:2, instance:testcases.TestCase1@6b419da]" name="doLogin" class="testcases.TestCase1"/>
        <method signature="TestCase1.doUserReg()[pri:1, instance:testcases.TestCase1@6b419da]" name="doUserReg" class="testcases.TestCase1"/>
        <method signature="TestCase3.doUserReg()[pri:1, instance:testcases.TestCase3@2cbb3d47]" name="doUserReg" class="testcases.TestCase3"/>
        <method signature="TestCase3.doLogin()[pri:2, instance:testcases.TestCase3@2cbb3d47]" name="doLogin" class="testcases.TestCase3"/>
      </group> <!-- functional -->
      <group name="Regression">
        <method signature="TestCase3.doUserReg()[pri:1, instance:testcases.TestCase3@2cbb3d47]" name="doUserReg" class="testcases.TestCase3"/>
        <method signature="TestCase3.doLogin()[pri:2, instance:testcases.TestCase3@2cbb3d47]" name="doLogin" class="testcases.TestCase3"/>
      </group> <!-- Regression -->
      <group name="Smoke">
        <method signature="TestCase2.validateTitle()[pri:0, instance:testcases.TestCase2@69930714]" name="validateTitle" class="testcases.TestCase2"/>
        <method signature="TestCase3.doUserReg()[pri:1, instance:testcases.TestCase3@2cbb3d47]" name="doUserReg" class="testcases.TestCase3"/>
      </group> <!-- Smoke -->
    </groups>
    <test name="Login Test" duration-ms="146" started-at="2021-04-07T13:02:42 IST" finished-at="2021-04-07T13:02:42 IST">
      <class name="testcases.TestCase1">
        <test-method status="PASS" signature="creatingDBConn()[pri:0, instance:testcases.TestCase1@6b419da]" name="creatingDBConn" is-config="true" duration-ms="1" started-at="2021-04-07T13:02:42 IST" finished-at="2021-04-07T13:02:42 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- creatingDBConn -->
        <test-method status="PASS" signature="launchBrowser()[pri:0, instance:testcases.TestCase1@6b419da]" name="launchBrowser" is-config="true" duration-ms="0" started-at="2021-04-07T13:02:42 IST" finished-at="2021-04-07T13:02:42 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method status="PASS" signature="doUserReg()[pri:1, instance:testcases.TestCase1@6b419da]" name="doUserReg" duration-ms="21" started-at="2021-04-07T13:02:42 IST" finished-at="2021-04-07T13:02:42 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doUserReg -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:testcases.TestCase1@6b419da]" name="closeBrowser" is-config="true" duration-ms="1" started-at="2021-04-07T13:02:42 IST" finished-at="2021-04-07T13:02:42 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method status="PASS" signature="launchBrowser()[pri:0, instance:testcases.TestCase1@6b419da]" name="launchBrowser" is-config="true" duration-ms="2" started-at="2021-04-07T13:02:42 IST" finished-at="2021-04-07T13:02:42 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method status="PASS" signature="doLogin()[pri:2, instance:testcases.TestCase1@6b419da]" name="doLogin" duration-ms="3" started-at="2021-04-07T13:02:42 IST" finished-at="2021-04-07T13:02:42 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogin -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:testcases.TestCase1@6b419da]" name="closeBrowser" is-config="true" duration-ms="1" started-at="2021-04-07T13:02:42 IST" finished-at="2021-04-07T13:02:42 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method status="PASS" signature="closeDBConn()[pri:0, instance:testcases.TestCase1@6b419da]" name="closeDBConn" is-config="true" duration-ms="1" started-at="2021-04-07T13:02:42 IST" finished-at="2021-04-07T13:02:42 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDBConn -->
      </class> <!-- testcases.TestCase1 -->
    </test> <!-- Login Test -->
    <test name="Validate Title Test" duration-ms="42" started-at="2021-04-07T13:02:43 IST" finished-at="2021-04-07T13:02:43 IST">
      <class name="testcases.TestCase2">
        <test-method status="FAIL" signature="validateTitle()[pri:0, instance:testcases.TestCase2@69930714]" name="validateTitle" duration-ms="29" started-at="2021-04-07T13:02:43 IST" finished-at="2021-04-07T13:02:43 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [Yahoo.com] but found [Google.com],
Title Didnt Match expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Yahoo.com] but found [Google.com],
Title Didnt Match expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at testcases.TestCase2.validateTitle(TestCase2.java:22)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1213)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<a href="E:\screenshot\error.jpg" target="_blank">Screenshot link</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a href="E:\screenshot\error.jpg" target="_blank"><img height=200 width=200 src="E:\screenshot\error.jpg"></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- validateTitle -->
      </class> <!-- testcases.TestCase2 -->
    </test> <!-- Validate Title Test -->
    <test name="Dependency Test" duration-ms="85" started-at="2021-04-07T13:02:43 IST" finished-at="2021-04-07T13:02:43 IST">
      <class name="testcases.TestCase3">
        <test-method status="FAIL" signature="doUserReg()[pri:1, instance:testcases.TestCase3@2cbb3d47]" name="doUserReg" duration-ms="1" started-at="2021-04-07T13:02:43 IST" finished-at="2021-04-07T13:02:43 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[User not registered Successfully]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: User not registered Successfully
at org.testng.Assert.fail(Assert.java:99)
at testcases.TestCase3.doUserReg(TestCase3.java:10)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1213)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<a href="E:\screenshot\error.jpg" target="_blank">Screenshot link</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a href="E:\screenshot\error.jpg" target="_blank"><img height=200 width=200 src="E:\screenshot\error.jpg"></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- doUserReg -->
        <test-method status="SKIP" signature="doLogin()[pri:2, instance:testcases.TestCase3@2cbb3d47]" name="doLogin" duration-ms="0" started-at="2021-04-07T13:02:43 IST" depends-on-methods="testcases.TestCase3.doUserReg" finished-at="2021-04-07T13:02:43 IST">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestCase3.doLogin()[pri:2, instance:testcases.TestCase3@2cbb3d47] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestCase3.doLogin()[pri:2, instance:testcases.TestCase3@2cbb3d47] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1213)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogin -->
      </class> <!-- testcases.TestCase3 -->
    </test> <!-- Dependency Test -->
    <test name="Failure Test" duration-ms="12" started-at="2021-04-07T13:02:43 IST" finished-at="2021-04-07T13:02:43 IST">
      <class name="testcases.TestFailure">
        <test-method status="PASS" signature="setUp()[pri:0, instance:testcases.TestFailure@501edcf1]" name="setUp" is-config="true" duration-ms="67" started-at="2021-04-07T13:02:42 IST" finished-at="2021-04-07T13:02:42 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="doLogin()[pri:0, instance:testcases.TestFailure@501edcf1]" name="doLogin" duration-ms="1" started-at="2021-04-07T13:02:43 IST" finished-at="2021-04-07T13:02:43 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failing the login test]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failing the login test
at org.testng.Assert.fail(Assert.java:99)
at testcases.TestFailure.doLogin(TestFailure.java:11)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1213)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<a href="E:\screenshot\error.jpg" target="_blank">Screenshot link</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a href="E:\screenshot\error.jpg" target="_blank"><img height=200 width=200 src="E:\screenshot\error.jpg"></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- doLogin -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:testcases.TestFailure@501edcf1]" name="tearDown" is-config="true" duration-ms="0" started-at="2021-04-07T13:02:43 IST" finished-at="2021-04-07T13:02:43 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testcases.TestFailure -->
    </test> <!-- Failure Test -->
  </suite> <!-- Functional Suite -->
</testng-results>
